### PR TITLE
bullseye support

### PR DESCRIPTION
**Pull request by oOHenry**

### CODE REVIEW

**Comment by skrivy** [comment]
We would appreciate merging this.

**Comment by oOHenry** [comment]
@jordiprats can you please take a look?

**Comment by jordiprats** [comment]
Hi,
I have merged your PR using [PR-5](https://github.com/SaltaIT/eyp-systemd/pull/5) adding credits for your contribution

thanks for checking that works fine with Debian 11!

**Comment by oOHenry** [comment]
Thanks for merging, when will 3.1.1 be available on puppet forge?

**Comment by jordiprats** [comment]
The github action that publishes it is no longer working, I need to take a look

**Pull request merged**
